### ISSUE TITLE
Basic performance testing

### ISSUE THREAD

**Issue by brendanarnold** [DFE-Digital/polis-whitelabel#29]
Some areas of pol.is lead to concern about the performance of the system under load - this ticket is to develop some basic load testing scripts to determine what the maximum number of concurrent participants in a debate could be.

It will also allow us to compare the mono-VM approach for hosting vs. multi-Container approach.

## Approach

* [Apache JMeter](https://jmeter.apache.org/) scripts tested locally
* Scripts loaded into [Azure Load Testing](https://azure.microsoft.com/en-us/products/load-testing) to try out load in a deployed environment
* Put basic logging in `file-server` to see if caching plays a part

## Possible areas to improve performance

* Refactor `file-server` to be non-blocking
* 'Front load' majority of static files to the caddy server
* Reduce volume of `server` logging

**Comment by patcon** [comment]
Related: 
- https://github.com/compdemocracy/polis/issues/274
- https://github.com/joshsmith2/polis-loadtesting

cc: @joshsmith2 (in case still interested in this at https://twitter.com/Demos 🙂 )
